language: node_js
node_js:
- "10"

# make use of vm's
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
- 'docker'

before_install:
- curl -sSL https://cli.openfaas.com | sudo sh
- cd wetternode && npm install && cd ..

script:
#- cd wetternode && npm run test && cd ..
- faas-cli build -f wetternode.yml

#notifications:
#  email:
#    recipients:
#    - xxx@gmail.com
#    on_success: change
#    on_failure: always

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin; fi
- docker tag tillkuhn/functions-wetternode:latest "tillkuhn/functions-wetternode:${TRAVIS_COMMIT}"
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then docker push "tillkuhn/functions-base64:${TRAVIS_COMMIT}"; fi